baseURL = 'https://fedemahf.github.io/gohugo-website/'
languageCode = 'en-us'
title = 'Federico Mahfoud'
disableKinds = ["taxonomy", "term"]

[menu]
[[menu.main]]
  identifier = 'home'
  name = 'home'
  title = 'home'
  url = '/'
  weight = 10
[[menu.main]]
  identifier = 'posts'
  name = 'posts'
  title = 'posts'
  url = '/posts/'
  weight = 20

[[menu.socials]]
  name = 'linkedin'
  url = 'https://linkedin.com/in/fedemahf'
  weight = 10
[[menu.socials]]
  name = 'github'
  url = 'https://github.com/fedemahf'
  weight = 20
[[menu.socials]]
  name = 'twitter'
  url = 'https://twitter.com/fedemahf'
  weight = 30


[params]
  description = ''
  images = ['favicon-32x32.png']
  title = ''

[outputs]
  home = ['html']
