baseURL = 'https://hitorilabs.com/'
languageCode = 'en-us'
title = 'hitorilabs'
disableKinds = ["taxonomy", "term"]

[menu]
[[menu.main]]
  identifier = 'home'
  name = 'home'
  title = 'hitorilabs | home'
  url = '/'
  weight = 10
[[menu.main]]
  identifier = 'posts'
  name = 'posts'
  title = 'hitorilabs | posts'
  url = '/posts/'
  weight = 20
[[menu.main]]
  identifier = 'log'
  name = 'log'
  title = 'hitorilabs | log'
  url = '/log/'
  weight = 30
  
[[menu.socials]]
  name = 'github'
  url = 'https://github.com/hitorilabs'
  weight = 10
[[menu.socials]]
  name = 'twitter'
  url = 'https://twitter.com/hitorilabs'
  weight = 20
[[menu.socials]]
  name = 'twitch'
  url = 'https://www.twitch.tv/hitorilabs'
  weight = 30
[[menu.socials]]
  name = 'mal'
  url = 'https://myanimelist.net/animelist/hitorilabs'
  weight = 40


[params]
  description = 'Independent research group working on software for AI'
  images = ['favicon-32x32.png']
  title = 'hitorilabs'

[outputs]
  home = ['html']
